# Generated by Django 6.1 on 2026-08-18 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='media/profile_images/default.jpg', upload_to='media/profile_images/'),
        ),
    ]
