# Generated by Django 6.1 on 2026-08-31 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0003_rename_message_feedback_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='profile_images/default.png', upload_to='profile_images/'),
        ),
        migrations.DeleteModel(
            name='ContactMessage',
        ),
    ]
