# Generated by Django 6.1 on 2026-09-01 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0005_contactmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='profile_images/default.jpg', upload_to='profile_images/'),
        ),
        migrations.DeleteModel(
            name='ContactMessage',
        ),
    ]
