# Generated by Django 6.1 on 2026-09-01 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0006_alter_profile_image_delete_contactmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='profile_images/1.jpg', upload_to='profile_images/'),
        ),
    ]
